### ISSUE TITLE
rgrid2rcm and chunking

### ISSUE THREAD

**Issue by jaredalee** [NCAR/geocat-comp#200]
I'm trying to regrid data from a rectilinear grid (CAMS) to a curvilinear grid (CMAQ), so I'm trying to use geocat.comp.rgrid2rcm. I'm including the code that will give information about the 

```
load geocat.comp

[code to obtain my arrays from the datasets]

print('-- Regridding the CAMS data to the CMAQ grid')
print(cams_lat)
print(cams_lat.shape)
print('')
print(cams_lon)
print(cams_lon.shape)
print('')
print(cams_o3_this_ppb)
print(cams_o3_this_ppb.shape)
print('')
print(cmaq_lat)
print(cmaq_lat.shape)
print('')
print(cmaq_lon)
print(cmaq_lon.shape)
print('')
cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat, cams_lon, cams_o3_this_ppb,  cmaq_lat, cmaq_lon)
```
That yields this output:

```
-- Regridding the CAMS data to the CMAQ grid
<xarray.DataArray 'latitude' (latitude: 88)>
array([20. , 20.4, 20.8, 21.2, 21.6, 22. , 22.4, 22.8, 23.2, 23.6, 24. , 24.4,
       24.8, 25.2, 25.6, 26. , 26.4, 26.8, 27.2, 27.6, 28. , 28.4, 28.8, 29.2,
       29.6, 30. , 30.4, 30.8, 31.2, 31.6, 32. , 32.4, 32.8, 33.2, 33.6, 34. ,
       34.4, 34.8, 35.2, 35.6, 36. , 36.4, 36.8, 37.2, 37.6, 38. , 38.4, 38.8,
       39.2, 39.6, 40. , 40.4, 40.8, 41.2, 41.6, 42. , 42.4, 42.8, 43.2, 43.6,
       44. , 44.4, 44.8, 45.2, 45.6, 46. , 46.4, 46.8, 47.2, 47.6, 48. , 48.4,
       48.8, 49.2, 49.6, 50. , 50.4, 50.8, 51.2, 51.6, 52. , 52.4, 52.8, 53.2,
       53.6, 54. , 54.4, 54.8], dtype=float32)
Coordinates:
  * latitude  (latitude) float32 20.0 20.4 20.8 21.2 ... 53.6 54.0 54.4 54.8
Attributes:
    units:      degrees_north
    long_name:  latitude
(88,)

<xarray.DataArray (longitude: 188)>
array([-135.      , -134.6     , -134.2     , -133.8     , -133.4     ,
       -133.      , -132.6     , -132.2     , -131.8     , -131.4     ,
       -131.      , -130.6     , -130.2     , -129.8     , -129.4     ,
       -129.      , -128.6     , -128.2     , -127.8     , -127.399994,
       -127.      , -126.600006, -126.2     , -125.8     , -125.399994,
       -125.      , -124.600006, -124.2     , -123.8     , -123.399994,
       -123.      , -122.600006, -122.2     , -121.8     , -121.399994,
       -121.      , -120.600006, -120.2     , -119.8     , -119.399994,
       -119.      , -118.600006, -118.2     , -117.8     , -117.399994,
       -117.      , -116.600006, -116.2     , -115.8     , -115.399994,
       -115.      , -114.600006, -114.2     , -113.8     , -113.399994,
       -113.      , -112.600006, -112.2     , -111.8     , -111.399994,
       -111.      , -110.600006, -110.2     , -109.8     , -109.399994,
       -109.      , -108.600006, -108.2     , -107.8     , -107.399994,
       -107.      , -106.600006, -106.2     , -105.8     , -105.399994,
       -105.      , -104.600006, -104.2     , -103.79999 , -103.399994,
       -103.      , -102.600006, -102.20001 , -101.79999 , -101.399994,
       -101.      , -100.600006, -100.20001 ,  -99.79999 ,  -99.399994,
        -99.      ,  -98.600006,  -98.20001 ,  -97.79999 ,  -97.399994,
        -97.      ,  -96.600006,  -96.20001 ,  -95.79999 ,  -95.399994,
        -95.      ,  -94.600006,  -94.20001 ,  -93.79999 ,  -93.399994,
        -93.      ,  -92.600006,  -92.20001 ,  -91.79999 ,  -91.399994,
        -91.      ,  -90.600006,  -90.20001 ,  -89.79999 ,  -89.399994,
        -89.      ,  -88.600006,  -88.20001 ,  -87.79999 ,  -87.399994,
        -87.      ,  -86.600006,  -86.20001 ,  -85.79999 ,  -85.399994,
        -85.      ,  -84.600006,  -84.20001 ,  -83.79999 ,  -83.399994,
        -83.      ,  -82.600006,  -82.20001 ,  -81.79999 ,  -81.399994,
        -81.      ,  -80.600006,  -80.20001 ,  -79.79999 ,  -79.399994,
        -79.      ,  -78.600006,  -78.20001 ,  -77.79999 ,  -77.399994,
        -77.      ,  -76.600006,  -76.20001 ,  -75.79999 ,  -75.399994,
        -75.      ,  -74.600006,  -74.20001 ,  -73.79999 ,  -73.399994,
        -73.      ,  -72.600006,  -72.20001 ,  -71.79999 ,  -71.399994,
        -71.      ,  -70.600006,  -70.20001 ,  -69.79999 ,  -69.399994,
        -69.      ,  -68.600006,  -68.20001 ,  -67.79999 ,  -67.399994,
        -67.      ,  -66.600006,  -66.20001 ,  -65.79999 ,  -65.399994,
        -65.      ,  -64.600006,  -64.20001 ,  -63.799988,  -63.399994,
        -63.      ,  -62.600006,  -62.200012,  -61.799988,  -61.399994,
        -61.      ,  -60.600006,  -60.200012], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 -135.0 -134.6 -134.2 ... -61.0 -60.6 -60.2
Attributes:
    units:      degrees_east
    long_name:  longitude
(188,)

<xarray.DataArray 'go3' (time: 1, latitude: 88, longitude: 188)>
array([[[29.994196, 29.91522 , 29.55502 , ..., 24.910906, 24.976397,
         25.053444],
        [30.023088, 29.82084 , 29.466413, ..., 24.826149, 24.926317,
         25.090046],
        [29.965303, 29.741861, 29.487602, ..., 24.487139, 24.596931,
         24.855047],
        ...,
        [31.766317, 33.124302, 34.30315 , ..., 26.442253, 25.481068,
         24.656647],
        [29.655182, 31.671934, 32.979836, ..., 27.665398, 28.39929 ,
         28.085316],
        [29.822765, 32.392338, 34.466877, ..., 30.169485, 31.080585,
         28.761415]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 225.0 225.4 225.8 226.2 ... 299.0 299.4 299.8
  * latitude   (latitude) float32 20.0 20.4 20.8 21.2 ... 53.6 54.0 54.4 54.8
  * time       (time) datetime64[ns] 2020-08-01
Attributes:
    units:          kg kg**-1
    long_name:      Ozone mass mixing ratio (full chemistry scheme)
    standard_name:  mass_fraction_of_ozone_in_air
(1, 88, 188)

<xarray.DataArray 'LAT' (latitude: 265, longitude: 442)>
[117130 values with dtype=float32]
Dimensions without coordinates: latitude, longitude
Attributes:
    long_name:  LAT             
    units:      DEGREES         
    var_desc:   latitude (south negative)                                    ...
(265, 442)

<xarray.DataArray 'LON' (latitude: 265, longitude: 442)>
[117130 values with dtype=float32]
Dimensions without coordinates: latitude, longitude
Attributes:
    long_name:  LON             
    units:      DEGREES         
    var_desc:   longitude (west negative)                                    ...
(265, 442)

Traceback (most recent call last):
  File "regrid_cams_to_cmaq.py", line 342, in <module>
    main()
  File "regrid_cams_to_cmaq.py", line 337, in main
    cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat, cams_lon, cams_o3_this_ppb,  cmaq_lat, cmaq_lon)
  File "/glade/u/apps/opt/conda/envs/npl-2202/lib/python3.7/site-packages/geocat/f2py/rcm2rgrid_wrapper.py", line 346, in rgrid2rcm
    if list(fi.chunks)[-2:] != [lat1d.shape, lon1d.shape]:
TypeError: 'NoneType' object is not iterable
```

As you can see, I'm passing rgrid2rcm xarray.DataArray variables, all with consistently named dimensions. I have no idea how to solve the chunking issue, though, as I've never dealt with chunking in my life. There's also nothing in the documentation for this function about chunking, so I have no idea what to do. Can someone please help me? Is this a bug? Is there something else I need to do differently?

I'm running on NCAR's Casper with npl-2202 for my Python environment.

Thanks,
Jared

**Comment by jaredalee** [comment]
Just wondering if the issue with rgrid2rcm is the same as the one mentioned in issue #126. It does seem like rgrid2rcm requires chunked xarray.DataArray variables, which seems suboptimal to me (especially when it's not clearly mentioned in documentation for functions), as not everyone wants to chunk variables or use dask. Is this an issue that's present across many other geocat-comp functions as well?

**Comment by erogluorhan** [comment]
Thanks for data sets! Just accessed them and will let you know soon what I find here!

**Comment by erogluorhan** [comment]
@jaredalee I found at least one bug in our implementation that we'd need to fix likely in this month's release, but am still working to get your case working. I will let you know

**Comment by erogluorhan** [comment]
Hi @jaredalee , `rcm2rgrid` function is also designed to work with either chunked or unchunked xarrays, as well as numpy arrays. However, there is an implementation error in the function. I am working on both fixing the bug to make a quick release (for this I will need to do some tests on my fix) and finding an intermediate usage for you while waiting for that bug-fix release.

**Comment by jaredalee** [comment]
Thanks for the update and for digging into this. Please do keep me posted as you find an intermediate solution and then do a bug-fix release.

**Comment by erogluorhan** [comment]
> 

I have a quick fix that would get your case working, but you'd need to clone geocat-f2py, build that from the source code after making a very little code change, then calling our function with converting all xarray inputs to numpy (simply by adding .values to each of them).

This'd be  about 15-30 minute fix on your end; please let me know if you'd like to try it, then I will give you step-by-step instructions. 

On my end before a release, I'd need to make sure my fixes are generic and unit-testing-safe so it would take more time to get a release done.

**Comment by jaredalee** [comment]
Sure, I can try that. Please send instructions when you're able. Do you think a bug fix release for this might come out next week, or would it be longer than that? And does this same bug also affect `rcm2rgrid`?

**Comment by erogluorhan** [comment]
We will do our best to release the bug-fix ASAP (would assume next week) but this bug might be combined with some other improvements; will keep you posted there. And yes, this bug is also applicable to `rcm2rgrid `. 

Below are what you can do in the meantime to get our case up and running:

1. Clone the geocat-f2py git repo to your glade working environment.
2. Go to geocat-f2py directory, then open the Python file /src/geocat/f2py/rcm2rgrid.py. Remove the part `coords=fo_coords` on the line 389; save the file.
3. Activate your conda environment in which you work with geocat-comp.
4. In the geocat-f2py root file, you will need to run `build.sh`. For this, you can refer to "Installing GeoCAT-f2py from source" at [GeoCAT-f2py Installation](https://github.com/NCAR/geocat-f2py/blob/main/INSTALLATION.md). Once you run build.sh, you will get the geocat-f2py version installed through conda in your conda environment replaced with one built from the source code you changed. 
5. Go to your use case, and run `rgrid2rcm` with all your inputs converted to numpy as follows:

    `cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon.values, cams_o3_this_ppb.values,  cmaq_lat.values, cmaq_lon.values)`

This worked on my end, and I hope it goes smoothly on your end, too. Please let me know if you need any further assistance.

**Comment by jaredalee** [comment]
I just tried all this (noting that the file after I cloned the repo is /src/geocat/f2py/rcm2rgrid_wrapper.py, not rcm2rgrid.py), but I get an error that geocat.comp cannot find rgrid2rcm:

```
Traceback (most recent call last):
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 358, in <module>
    main()
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 346, in main
    cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon.values, cams_o3_this_ppb.values,  cmaq_lat.values, cmaq_lon.values)
AttributeError: module 'geocat.comp' has no attribute 'rgrid2rcm'
```

It might be worth noting here that runing `pytest test` as suggested on the geocat-f2py installation from source guide yielded quite a few errors:

```
[snip]
____________________________________ ERROR collecting test/test_rcm2rgrid_2.py _____________________________________
ImportError while importing test module '/glade/work/jaredlee/python/geocat/geocat-f2py/test/test_rcm2rgrid_2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../conda-envs/geocat_f2py_build/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_rcm2rgrid_2.py:14: in <module>
    from geocat.f2py import rcm2rgrid
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/__init__.py:4: in <module>
    from .dpres_plevel_wrapper import dpres_plevel
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/dpres_plevel_wrapper.py:5: in <module>
    from .fortran import dpresplvl
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/fortran/__init__.py:1: in <module>
    from .dpres_plevel import (dpresplvl)
E   ModuleNotFoundError: No module named 'geocat.f2py.fortran.dpres_plevel'
_____________________________________ ERROR collecting test/test_rgrid2rcm.py ______________________________________
ImportError while importing test module '/glade/work/jaredlee/python/geocat/geocat-f2py/test/test_rgrid2rcm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../conda-envs/geocat_f2py_build/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_rgrid2rcm.py:14: in <module>
    from geocat.f2py import rgrid2rcm
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/__init__.py:4: in <module>
    from .dpres_plevel_wrapper import dpres_plevel
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/dpres_plevel_wrapper.py:5: in <module>
    from .fortran import dpresplvl
../../../conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/fortran/__init__.py:1: in <module>
    from .dpres_plevel import (dpresplvl)
E   ModuleNotFoundError: No module named 'geocat.f2py.fortran.dpres_plevel'
[snip]
============================================= short test summary info ==============================================
ERROR test/test_dpres_plevel.py
ERROR test/test_grid_to_triple.py
ERROR test/test_linint2.py
ERROR test/test_linint2pts.py
ERROR test/test_moc_globe_atl.py
ERROR test/test_rcm2points.py
ERROR test/test_rcm2rgrid.py
ERROR test/test_rcm2rgrid_2.py
ERROR test/test_rgrid2rcm.py
ERROR test/test_triple_to_grid.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 10 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 10 errors in 11.42s ================================================ 
```

So presumably something is messed up with my conda environment... Does it matter that I had to run `pip install geocat-comp` before running this script? Did that introduce some sort of mismatch that caused my script not to find the rcm2rgrid module?

**Comment by jaredalee** [comment]
Based on your comments I went back to my build of geocat-f2py from source. I found that the problem was that I had intel compilers loaded, not gnu compilers. Once I made that switch, `build.sh` worked fine, and `pytest test`  passed all tests. (I built geocat-f2py from source in a new Python environment as the instruction guide said to do, rather than building it within my NCAR python environment—it wasn't clear to me that I could do that. That's why I needed to run `pip install geocat-comp` as well.)

Then when I re-ran my code, my call to geocat.comp.rgrid2rcm (with your modifications to the arguments, specifying numpy arrays rather than xarray DataArrays) worked properly! Thanks so much for your help! So now I have a temporary python environment in which I can run this, but I'll definitely update geocat-f2py in my regular Python environment once the bug fix is released.

Out of curiosity, is there a design reason behind requiring numpy arrays and not xarray DataArrays in the arguments to rgrid2rcm?

**Comment by jaredalee** [comment]
Maybe this is part of other bugs that will be fixed in the upcoming release, but I've found something quite curious. When I have these lines of code:

```
print('   Regridding O3 Option 1')
cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon.values, cams_o3_this_ppb.values,  cmaq_lat.values, cmaq_lon.values)
cams_lon2 = cams_lon.values
print('   Regridding O3 Option 2')
cams_o3_ppb_regrid = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon2, cams_o3_this_ppb, cmaq_lat.values, cmaq_lon.values)
```

The first option works fine, but the second option throws an error:

```
   Regridding O3 Option 1
   Regridding O3 Option 2
Traceback (most recent call last):
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 351, in <module>
    main()
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 338, in main
    cams_o3_ppb_regrid = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon2, cams_o3_this_ppb, cmaq_lat.values, cmaq_lon.values)
  File "/glade/work/jaredlee/conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/rcm2rgrid_wrapper.py", line 346, in rgrid2rcm
    if list(fi.chunks)[-2:] != [lat1d.shape, lon1d.shape]:
TypeError: 'NoneType' object is not iterable
```

I'm not understanding why the function works when I pass cams_lon.values as my 1d longitude variable to rgrid2rcm, but it simultaneously fails when I pass cams_lon2 (which is set to cams_lon.values) as my 1d longitude variable. Is this another bug?

**Comment by erogluorhan** [comment]
> 

In fact, this function and all the others (if I am not missing any) under GeoCAT-comp are designed to consume Xarray inputs. However, it turns out we forgot to add that information into the function documentation as well as we had a bug with Xarray inputs in this specific function (and maybe rcm2rgrid). The upcoming bug-fix release will get the functions working with Xarray inputs just fine (to fix the existing bug of yours right away), and one more release will touch the documentation and maybe more codes to get the things improved.

**Comment by erogluorhan** [comment]
> Maybe this is part of other bugs that will be fixed in the upcoming release, but I've found something quite curious. When I have these lines of code:
> 
> ```
> print('   Regridding O3 Option 1')
> cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon.values, cams_o3_this_ppb.values,  cmaq_lat.values, cmaq_lon.values)
> cams_lon2 = cams_lon.values
> print('   Regridding O3 Option 2')
> cams_o3_ppb_regrid = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon2, cams_o3_this_ppb, cmaq_lat.values, cmaq_lon.values)
> ```
> 
> The first option works fine, but the second option throws an error:
> 
> ```
>    Regridding O3 Option 1
>    Regridding O3 Option 2
> Traceback (most recent call last):
>   File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 351, in <module>
>     main()
>   File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 338, in main
>     cams_o3_ppb_regrid = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon2, cams_o3_this_ppb, cmaq_lat.values, cmaq_lon.values)
>   File "/glade/work/jaredlee/conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/f2py/rcm2rgrid_wrapper.py", line 346, in rgrid2rcm
>     if list(fi.chunks)[-2:] != [lat1d.shape, lon1d.shape]:
> TypeError: 'NoneType' object is not iterable
> ```
> 
> I'm not understanding why the function works when I pass cams_lon.values as my 1d longitude variable to rgrid2rcm, but it simultaneously fails when I pass cams_lon2 (which is set to cams_lon.values) as my 1d longitude variable. Is this another bug?

That bug is most likely because I can see that in the second example, you called the function with the `cams_o3_this_ppb` data array argument in Xarray format (i.e. not with `.values`), so it looks basically like the exact same bug we mentioned so far.

**Comment by erogluorhan** [comment]
Hi @jaredalee the bug-fix for GeoCAT-f2py is released at Anaconda and PyPI, so please `conda install` or `pip install` it and give it a try when you have time. I confirmed that rgrid2rcm works with both Numpy and Xarray (either chunked or unchunked) inputs, but please let me know if you encounter any issues. 

Please note this is a quick bug-fix release to get you up and running with the function, but we are currently working on releasing a much-improved version for better documentation and fixed potential bugs with other functions.

**Comment by jaredalee** [comment]
Hi @erogluorhan, I finally got around to testing your updated geocat-f2py release, but it seems to have broken things. Now I'm getting this error:

```
(geocat_f2py_build) -bash-4.2$ python3 regrid_cams_to_cmaq.py 
Reading CMAQ coordinate data from /glade/campaign/ral/nsap/JTTI/bcdata/aqm.t12z.grdcro2d.ncf
Processing CAMS data from 2020-08-01_00
-- Regridding the CAMS data to the CMAQ grid
Traceback (most recent call last):
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 382, in <module>
    main()
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 347, in main
    cams_o3_ppb_regrid  = geocat.comp.rgrid2rcm(cams_lat.values, cams_lon.values, cams_o3_this_ppb.values,  cmaq_lat.values, cmaq_lon.values)
AttributeError: module 'geocat.comp' has no attribute 'rgrid2rcm'
```

I get the same error regardless of which conda environment I have activated, whether the environment based/cloned off of the NCAR Python Library, or the custom one I made for custom-installing your prior interim fixes for the `rgrid2rcm` function. Even when I try adding this to the top of my script:

`from geocat.comp import rgrid2rcm`

I get this error:

```
(geocat_f2py_build) -bash-4.2$ python3 regrid_cams_to_cmaq.py 
Traceback (most recent call last):
  File "/glade/u/home/jaredlee/tools/python/NOAA_CMAQ_AnEn/regrid_cams_to_cmaq.py", line 28, in <module>
    from geocat.comp import rgrid2rcm
ImportError: cannot import name 'rgrid2rcm' from 'geocat.comp' (/glade/work/jaredlee/conda-envs/geocat_f2py_build/lib/python3.10/site-packages/geocat/comp/__init__.py)
```

The only thing that changed in my environment from before when the interim fixes were working was doing `pip install --upgrade geocat-f2py` to version 2022.2.0.

**Comment by erogluorhan** [comment]
Hi @jaredalee , thanks a lot for the feedback! I will look into it as soon as I can and will let you know.

**Comment by erogluorhan** [comment]
Hi @jaredalee , I had a chance to look into it this morning. Here are my findings; I hope they are helpful for you:

- The issue you are having looks like a namespace issue, but in fact, I didn't make any changes that would impact the geocat.comp namespace handling.
- However, your feedback allowed me to double-check our conda release files and I noticed I did only upload OSX version of geocat-f2py for Python 3.9 to Anaconda. I now uploaded both Linux and OSX versions for Python 3.7, 3.8, and 3.9. 
- I gave a try to updating an older version geocat-f2py in one of my existing conda environments via `conda update geocat-f2py` to v2022.02.0, and the import statements you had failure with works without an issue.
- You said that you attempted to upgrade geocat-f2py via `pip` instead of `conda`. As conda seems to work without an issue, I'd recommend you to use conda for now. For `pip` (i.e. PyPI), there should not have been any issue as we were generating wheels for platforms, but I can confirm that pip-version of geocat-f2py has this import issue on my end. We will work on PyPI part, but, I do not expect you to have this issue if you install/update geocat-f2py via conda.

**Comment by jaredalee** [comment]
Hi @erogluorhan, thank you much for those suggestions. After updating via `conda update geocat-f2py`, now my script works perfectly. I believe at this point the issue can be closed from my perspective, unless you need to keep it open until the the PyPI issues are fixed and the future more comprehensive update is released. I really appreciate all your help in getting this function to work for me!

**Comment by erogluorhan** [comment]
That sounds great, @jaredalee ! Let me keep this open until I think I have addressed other things (PyPI and improvements); I'd close after then. We also welcome your feedback regarding `rgrid2rcm` performance if you get to experience any. 

Best,

**Comment by erogluorhan** [comment]
Hi @jaredalee , as we now released the comprehensive improvements as well as scheduled the PyPI fix in our agenda, we are good to close this issue. I'd also like to say that we are working on our documentations to include some NCAR HPC-related guidance as you pointed out in Issue #199. 

Please feel always free to provide your feedback, reports, requests!
